@startuml
'https://plantuml.com/class-diagram

'----Classification layer centered at Classifier API. The classifier connects to a document and classifies
'----the text into spans, where each span contains sufficient info for use cases such as syntax highlighting.
'----Client of this API will provide the classifier a callback that will be call each time the classification changed,
'----i.e. underlying document changed and the classification spans updated.
interface Classifier {
    +void connect(TSDocument document)
    +void addClassificationListener(ClassificationListener listener)
}

interface ClassificationListener {
    +void initialize(List<ClassificationSpan> spans)
    +void classificationUpdated(List<ClassificationSpan> spans)
}

class ClassificationSpan {
    +int offset()
    +int length()
    +ClassificationType classificationType()
}

interface ClassificationType {
    +String getName()
    +List<ClassificationType> getBaseTypes()
    +boolean isOfType(ClassificationType type)
}

'----Document layer centered at TSDocument API. A TSDocument is a logical presentation of a text document.
'----The actual read/write in the underlying document is managed by a text editor framework, e.g. Eclipse editor.
'----A TSDocument connect to the editor by a TextBuffer that provides reading services and notifies the TSDocument when
'----underlying text changed. By accessing the underlying text, the TSDocument not only provides basic text reading but
'----also provides APIs related to SyntaxTree of the text.
interface TSDocument {
    +TextBuffer getTextBuffer()
    +DocumentDescriptor getDescriptor()
    +void addTreeUpdateListener(TreeUpdateListener listener)
    +void addTreeUpdateStrategy(TreeUpdateStrategy strategy)
    +String getText()
    +String getText(int offset, _Point point)
}

interface SyntaxTree {
    +_Tree getUnderlyingTree()
    +String getLanguage()
    +List<SyntaxTree> getInjectedTrees()
}

interface TreeUpdateStrategy {
    +boolean shouldUpdate(List<BufferChange> changes)
}

interface TreeUpdateListener {
    +void initialize(SyntaxTree tree)
    +void treeUpdated(SyntaxTree oldTree, SyntaxTree newTree)
}

interface DocumentManager {
    +getDocument(DocumentDescriptor dd)
}

class DocumentDescriptor {
    +String project()
    +String name()
    +String mainLanguage()
    +boolean shouldIncludeInjectedLanguages();
}

'----Text buffer layer is an immediate layer between TSDocument and the underlying text document the TSDocument
'----representing, while the underlying document could come from a text editor framework like that of Eclipse.
interface TextBuffer {
    +String getText()
    +String getText(int fromOffset, _Point toPoint)
    +String getModificationStamp()
    +void addChangeConsumer(BufferChangeConsumer consumer)
    +SerialScheduler getChangeScheduler();
}

interface BufferChangeConsumer {
    void accept(BufferChange change)
}

class BufferChange {
    +long modificationStamp()
    +int startByte()
    +int oldEndByte()
    +int newEndByte()
    +_Point startPoint()
    +_Point oldEndPoint()
    +_Point newEndPoint()
}

'----A helper layer centered at DocumentCheckpoint API. A checkpoint semantically takes a snapshot of a document at
'----a particular point in time, and becomes invalid as soon as the text of the document changed.
'----The API provides execution services for use to ensure that any computations and state updates done in scope of a valid
'----checkpoint will be applied correctly and any such computations/updates done in scope of an invalid checkpoint will cause no harm
'----and possibly be canceled early to save resources.
interface DocumentCheckpoint {
    +{static} boolean isBound()
    +{static} DocumentCheckpoint boundCheckpoint()
    +boolean isValid()
    +DocumentCheckpoint addInvalidationCallback(Runnable callback)
    +<V> CheckpointTask<V> execute(Callable<V> task)
    +<V> CheckpointTask<V> executeAsync(Callable<V> task)
    +CheckpointTask<Void> execute(Runnable task)
    +CheckpointTask<Void> executeAsync(Runnable task)
}

interface CheckpointTask<V> {
    +CheckpointTask<V> onFailed(Runnable callback)
    +CheckpointTask<V> thenConsume(Consumer<V> consumer)
    +CheckpointTask<V> thenConsumeSerially(Consumer<V> consumer)
    +CheckpointTask<V> thenConsumeSerially(Consumer<V> consumer, SerialScheduler scheduler)
}

interface CheckpointManager {
    +void registerDocument(TSDocument document)
    +DocumentCheckpoint newCheckpointFor(TSDocument document)
}

interface SerialScheduler {
    +void submit(Runnable task)
}

'----Low level parsing layer that wraps and manages tree-sitter parsers,
'----used by TSDocument layer to build syntax trees----
interface ParserManager {
    +SafeParser getParser(ParserDescriptor pd)
    +List<ParserDescriptor> getDescriptorsByLanguage(String lang)
}

interface SafeParser {
    +void close()
    +_Parser unwrap()
    +parse(String text, Tree oldTree, Range includeRange)
    +void cancelParsing()
}

class ParserDescriptor {
    +String language()
    +String library()
    +String injectionQuery()
}

class "_Parser" <<TreeSitter API>>

class "_Tree" <<TreeSitter API>>

class "_Point" <<TreeSitter API>> {
    +int row()
    +int column()
}

@enduml